server:
  port: 19080
  encoding:
    force: true
    charset: UTF-8
    enabled: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: adminUserAuth
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.244.128:8848/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.244.128:3306/db_gao_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    password: 123456
    connection-init-sqls: set names utf8mb4
    initial-size: 20
    max-active: 100
    min-idle: 20
    max-wait: 60000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters: stat
pagehelper:
  helperDialect: mysql
mybatis:
  configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl